"""add_description_and_price_to_plans

Revision ID: 75ac154edbe3
Revises: 0001_initial_schema
Create Date: 2026-05-22 17:02:23.934706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ac154edbe3'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('plans', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.alter_column('plans', 'price', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'price')
    op.drop_column('plans', 'description')
    # ### end Alembic commands ###
