"""add_release_date_and_age_rating_to_videos

Revision ID: dfe4beb5fd17
Revises: 75ac154edbe3
Create Date: 2026-05-22 17:07:00.921091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe4beb5fd17'
down_revision: Union[str, None] = '75ac154edbe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('release_date', sa.Date(), nullable=True))
    op.add_column('videos', sa.Column('age_rating', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'age_rating')
    op.drop_column('videos', 'release_date')
    # ### end Alembic commands ###
